name: ai-dispatch
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  smoke-e2e:
    if: contains(github.event.comment.body, '/agent smoke e2e')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gate trusted sender
        uses: actions/github-script@v7
        with:
          script: |
            const sender = context.payload.comment.user.login;
            const owner  = context.repo.owner;
            const { data: perm } = await github.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              username: sender
            });
            if (!['admin','write','maintain'].includes(perm.permission) && sender !== owner) {
              core.setFailed(`not trusted: ${sender}`);
            }
      - name: Touch to trigger e2e
        run: |
          ts=$(date +%Y%m%d-%H%M%S)
          mkdir -p .chore/ci_touch
          echo ok > ".chore/ci_touch/e2e_smoke_${ts}.txt"
      - name: Create PR for smoke
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(ci-touch): trigger e2e smoke"
          title: "chore: e2e smoke via /agent"
          body: "Auto-created by /agent. Label 'e2e-required' で E2E 実行＆Playwrightレポート保存。"
          branch: chore/ci-touch-e2e
          delete-branch: true
          labels: e2e-required
