name: ai-dispatcher
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * MON'
permissions:
  contents: write
  pull-requests: write
jobs:
  dispatch:
    if: >
      github.event.comment.user.login == github.repository_owner &&
      startsWith(github.event.comment.body, '/ai ')
    runs-on: ubuntu-latest
    steps:
      - name: Parse command
        id: cmd
        run: |
          cmd="${{ github.event.comment.body }}"
          cmd="${cmd#'/ai '}"
          echo "cmd=$cmd" >> $GITHUB_OUTPUT
      - name: Update all behind
        if: steps.cmd.outputs.cmd == 'update all'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --state open --json number,mergeStateStatus \
            --jq '.[] | [.number,.mergeStateStatus] | @tsv' |
          while IFS=$'\t' read -r num state; do
            [ "$state" = "BEHIND" ] && gh api -X PUT "repos/${GITHUB_REPOSITORY}/pulls/$num/update-branch" || true
          done
      - name: Arm auto-merge all
        if: steps.cmd.outputs.cmd == 'merge all'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for n in $(gh pr list --state open --json number --jq '.[].number'); do
            gh pr merge "$n" --squash --delete-branch --auto || true
          done
      - name: Status
        if: steps.cmd.outputs.cmd == 'status'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --state open --json number,title,mergeStateStatus,autoMergeRequest \
            --jq '.[] | [.number,(if .autoMergeRequest then "ARMED" else "NOT-ARMED" end),.mergeStateStatus,.title] | @tsv'

  env-hardening:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run env hardening dispatch
        run: |
          mkdir -p artifacts/agent_reports
          python -m scripts.agents.dispatcher --task env_hardening --payload "{}" | tee artifacts/agent_reports/env_hardening.json
      - name: Upload env hardening result
        uses: actions/upload-artifact@v4
        with:
          name: agent-env-hardening
          path: artifacts/agent_reports/env_hardening.json
