name: auto-retry-build

x-agents-concurrency: &agents_concurrency
  group: agents-${{ (github.event.pull_request.number != null && format('pr-{0}', github.event.pull_request.number)) || github.ref }}
  cancel-in-progress: true

concurrency: *agents_concurrency

on:
  workflow_run:
    workflows: ["build-test","ai-agent-review","agent-runner"]
    types: [completed]
permissions:
  actions: write
  checks: read
jobs:
  retry:
    if: >
      github.event.workflow_run.conclusion == 'failure' ||
      github.event.workflow_run.conclusion == 'cancelled'
    runs-on: ubuntu-latest
    steps:
      - name: Re-run once
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X POST repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.event.workflow_run.id }}/rerun || true
