name: auto-retry-build
on:
  workflow_run:
    workflows: ["build-test","ai-agent-review","agent-runner"]
    types: [completed]
permissions:
  actions: write
  checks: read
jobs:
  retry:
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'cancelled' }}
    runs-on: ubuntu-latest
    steps:
      - name: Re-run once
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}
          gh api -X POST repos/${GITHUB_REPOSITORY}/actions/runs/$RUN_ID/rerun || true
