name: workflow-lint
on:
  pull_request:
    paths: [".github/workflows/*.yml"]
  push:
    branches: [main]
    paths: [".github/workflows/*.yml"]

concurrency:
  group: workflow-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
